sudo: required
language: python
python:
    - "2.7"
addons:
cache: pip
services:
before_install:
    - sudo apt-get update
install:
    - pip install -r requirements.txt
    - pip install coveralls
before_script:
    - python setup.py install
script:
    - coverage run setup.py test
before_cache:
after_success:
    - coverage combine
    - coveralls
after_failure:
before_deploy:
deploy:
after_deploy:
after_script:
